build: migrate from qmake to CMake
- Replace qmake-based build with CMake (requires 3.16+)
- Add root CMakeLists.txt and src/ui/CMakeLists.txt
- Update configure script to invoke cmake instead of qmake
- Add convenience Makefile wrapper (./configure && make still works)
- Update CI workflows to use cmake
- Tested on macOS arm64 with Qt 6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,25 +2,15 @@
 # Don't set `-e'!
 
 # Basic environment variables
-test -n "$MAKE"      || MAKE="make"
-test -n "$CXX"       || CXX="c++"
-test -n "$QTCHOOSER" || QTCHOOSER="$(command -v qtchooser 2> /dev/null)"
-test -n "$TMPDIR"    || TMPDIR="$PWD"
-
-# Use qtchooser if we have it, otherwise use Posix command -v
-if test -n "$QTCHOOSER"; then
-    test -n "$QMAKE"    || QMAKE="$QTCHOOSER -run-tool=qmake -qt=5"
-    test -n "$LRELEASE" || LRELEASE="$QTCHOOSER -run-tool=lrelease -qt=5"
-else
-    test -n "$QMAKE"    || QMAKE="$(command -v qmake-qt5 2>/dev/null || command -v qmake 2>/dev/null)"
-    test -n "$LRELEASE" || LRELEASE="$(command -v lrelease-qt5 2>/dev/null || command -v lrelease 2>/dev/null)"
-fi
-
+test -n "$MAKE"   || MAKE="make"
+test -n "$CXX"    || CXX="c++"
+test -n "$CMAKE"  || CMAKE="$(command -v cmake 2>/dev/null)"
+test -n "$TMPDIR" || TMPDIR="$PWD"
 
 errorExit() {
-    echo $1
+    echo "$1"
     test x"$2" != x"1" || fail_on_missing="yes"
-    test $fail_on_missing != "yes" || exit 1
+    test "$fail_on_missing" != "yes" || exit 1
 }
 
 help() {
@@ -38,43 +28,39 @@ Defaults for the options are specified in brackets.
   --prefix PREFIX,
   --prefix=PREFIX         install files in PREFIX [/usr/local]
 
-  -d, --debug             build with debugging symbols intact
+  -d, --debug             build in Debug mode (default: Release)
 
   --fail-on-missing       return exit 1 if non-optional components are missing
 
-  --lrelease COMMAND,
-  --lrelease=COMMAND      specify lrelease command [$LRELEASE]
+  --cmake COMMAND,
+  --cmake=COMMAND         specify cmake command [$CMAKE]
 
-  --qmake COMMAND,
-  --qmake=COMMAND         specify qmake command [$QMAKE]
-  --qmake-args ARGS       arguments to pass directly to qmake
+  -- ARGS...              extra arguments passed directly to cmake
 
 Some influential environment variables:
   MAKE        make command
   CXX         C++ compiler
-  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
-              nonstandard directory <lib dir>
-  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
-              you have headers in a nonstandard directory <include dir>
+  CMAKE       cmake command
+  LDFLAGS     linker flags
+  CPPFLAGS    preprocessor flags
   CXXFLAGS    C++ compiler flags
 
 EOF
 }
 
-# check "toolname/description" "command" errorExit
-# set errorExit to 1 for an error exit, otherwise leave it empty.
-# examples:
-# check "a Git client tool" git
-# check c++ g++ 1
+# check "description" "command" errorExit
 check() {
     printf "checking for $1... "
-    t=$(basename $2)
-    command -v $t 2>/dev/null 1>/dev/null
-    test $(echo $?) -eq 0 && echo "$(command -v $t)" || errorExit "not found!" $3
+    t=$(basename "$2")
+    command -v "$t" 2>/dev/null 1>/dev/null
+    test $? -eq 0 && echo "$(command -v "$t")" || errorExit "not found!" "$3"
 }
 
-
 fail_on_missing="no"
+BUILDTYPE="Release"
+PREFIX=""
+EXTRA_CMAKE_ARGS=""
+
 while [ "$#" -ge 1 ]; do
     key="$1"
     shift
@@ -85,114 +71,99 @@ while [ "$#" -ge 1 ]; do
         exit 0
         ;;
         -d|--debug)
-        BUILDMODE="debug"
+        BUILDTYPE="Debug"
         echo "WARNING: Building in debug mode!"
         ;;
-        --prefix=*) # --prefix=<something>
+        --prefix=*)
         PREFIX="${key#*=}"
         ;;
-        --prefix) # --prefix <something>
+        --prefix)
         PREFIX="$1"
         shift
         ;;
         --fail-on-missing)
         fail_on_missing="yes"
         ;;
-        --lrelease=*)
-        LRELEASE="${key#*=}"
+        --cmake=*)
+        CMAKE="${key#*=}"
         ;;
-        --lrelease)
-        LRELEASE="$1"
+        --cmake)
+        CMAKE="$1"
         shift
         ;;
-        --qmake=*)
-        QMAKE="${key#*=}"
-        ;;
-        --qmake)
-        QMAKE="$1"
-        shift
-        ;;
-        --qmake-args)
-        # Leave qmake args in $@
+        --)
+        # Everything after -- is passed to cmake
+        EXTRA_CMAKE_ARGS="$*"
         break
         ;;
         *)
-        echo WARNING: Unknown option "$key"
+        echo "WARNING: Unknown option '$key'"
         ;;
     esac
 done
 
+# --- dependency checks ---
+printf "checking for cmake... "
+$CMAKE --version 2>/dev/null 1>/dev/null
+test $? -eq 0 && echo "$CMAKE ($($CMAKE --version | head -1))" || \
+    errorExit "not found!\n  Install CMake 3.16+ or specify --cmake /path/to/cmake." 1
 
-# check for QT5 qmake
-printf "checking for QT5 qmake... "
-$QMAKE -help 2>/dev/null 1>/dev/null
-test $? -eq 0 && echo "$QMAKE" || \
-    errorExit "not found!\n  Try to run configure with \`--qmake /path/to/qmake-executable'." 1
-
-# check for lrelease
-printf "checking for lrelease... "
-$LRELEASE -help 2>/dev/null 1>/dev/null
-test $? -eq 0 && echo "$LRELEASE" || \
-    errorExit "not found!\n  Try to run configure with \`--lrelease /path/to/lrelease-executable'." 1
-
-check c++ "$CXX" 1
+check "c++" "$CXX" 1
+check "make" "$MAKE" 1
+check "pkg-config" pkg-config 1
 
 # check C++ compiler functionality
-rm -f test test.cpp
+rm -f "$TMPDIR/test" test.cpp
 cat << EOF > test.cpp
 #include <iostream>
-
-int main()
-{
-  std::cout << "Hello World!" << std::endl;
-  return 0;
-}
+int main() { std::cout << "Hello World!" << std::endl; return 0; }
 EOF
 printf "checking whether c++ compiler builds test program... "
-$CXX -o "$TMPDIR/test" test.cpp && echo "ok" || errorExit "error!" 1
-printf "checking whether c++ compiler supports -std=c++0x... "
-rm -f test
-$CXX -std=c++0x -o "$TMPDIR/test" test.cpp && echo "ok" || errorExit "error!" 1
+$CXX -std=c++17 -o "$TMPDIR/test" test.cpp && echo "ok" || errorExit "error!" 1
 printf "checking whether compiled test program works... "
 "$TMPDIR/test" 2>/dev/null 1>/dev/null && echo "ok" || errorExit "error!" 1
 rm -f "$TMPDIR/test" test.cpp
 
-check make "$MAKE" 1
-check pkg-config pkg-config 1
-
-# check for libraries via pkg-config
-# Detect Qt major version to use correct pkg-config names
-qt_major_version=$($QMAKE -query QT_VERSION 2>/dev/null | cut -d. -f1)
-if [ "$qt_major_version" = "6" ]; then
-    libraries="Qt6Core Qt6Gui Qt6Network Qt6WebEngineCore Qt6Widgets Qt6WebEngineWidgets Qt6PrintSupport Qt6Svg Qt6WebSockets Qt6WebChannel uchardet"
-else
-    libraries="Qt5Core Qt5Gui Qt5Network Qt5WebEngine Qt5Widgets Qt5WebEngineWidgets Qt5PrintSupport Qt5Svg Qt5WebSockets Qt5WebChannel uchardet"
-fi
-# Add DBus only on non-macOS platforms
+# check for Qt6 via pkg-config (informational; cmake does the real check)
+libraries="Qt6Core Qt6Gui Qt6Network Qt6WebEngineCore Qt6Widgets Qt6WebEngineWidgets Qt6PrintSupport Qt6Svg Qt6WebSockets Qt6WebChannel uchardet"
 if [ "$(uname -s)" != "Darwin" ]; then
-    if [ "$qt_major_version" = "6" ]; then
-        libraries="$libraries Qt6DBus"
-    else
-        libraries="$libraries Qt5DBus"
-    fi
+    libraries="$libraries Qt6DBus"
 fi
 for l in $libraries ; do
     printf "checking for ${l} library... "
-    pkg-config --libs $l 2>/dev/null 1>/dev/null
-    test $(echo $?) -eq 0 && pkg-config --libs $l || errorExit "not found!"
+    pkg-config --libs "$l" 2>/dev/null 1>/dev/null
+    test $? -eq 0 && pkg-config --libs "$l" || errorExit "not found!"
 done
 
-if [ -f "Makefile" ]; then
-    make distclean 2>/dev/null 1>/dev/null || true
+# --- clean previous build ---
+if [ -f "build/CMakeCache.txt" ]; then
+    echo ""
+    echo "Cleaning previous CMake configuration..."
+    rm -rf build
 fi
 
+# --- generate build system ---
+echo ""
+echo "Generating build system with CMake..."
 
-printf "generate Makefile... "
+CMAKE_ARGS="-S . -B build -DCMAKE_BUILD_TYPE=$BUILDTYPE -DCMAKE_CXX_COMPILER=$CXX"
+if [ -n "$PREFIX" ]; then
+    CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=$PREFIX"
+fi
+if [ -n "$CXXFLAGS" ] || [ -n "$CPPFLAGS" ]; then
+    CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_CXX_FLAGS=\"$CXXFLAGS $CPPFLAGS\""
+fi
+if [ -n "$LDFLAGS" ]; then
+    CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_EXE_LINKER_FLAGS=\"$LDFLAGS\""
+fi
+if [ -n "$EXTRA_CMAKE_ARGS" ]; then
+    CMAKE_ARGS="$CMAKE_ARGS $EXTRA_CMAKE_ARGS"
+fi
 
-$QMAKE PREFIX="$PREFIX" \
-QMAKE_CXX="$CXX" \
-QMAKE_CXXFLAGS="$CXXFLAGS $CPPFLAGS" \
-QMAKE_LFLAGS="$LDFLAGS" \
-LRELEASE="$LRELEASE" \
-CONFIG+="$BUILDMODE" \
-"$@" notepadqq.pro && echo "done" || errorExit "error!" 1
+echo "$CMAKE $CMAKE_ARGS"
+eval $CMAKE $CMAKE_ARGS || errorExit "CMake configuration failed!" 1
+
+echo ""
+echo "Configuration complete. Now run:"
+echo "  make          # or: cmake --build build -j\$(nproc)"
+echo "  make install  # or: cmake --install build"
